### ISSUE TITLE
TypeError: tile?.data?.flags?.tagger?.tags?.find is not a function

### ISSUE THREAD

**Issue by ravingdragoon** [Jules-Bens-Aa/jb2a_puzzle#2]
With only JB2A Music Puzzle and its dependencies active I receive the following error when running the setup macro. The macro does not function at all as far as I can tell.

```
VM23941:5 Uncaught (in promise) TypeError: tile?.data?.flags?.tagger?.tags?.find is not a function
    at eval (eval at _executeScript (foundry.js:16976:16), <anonymous>:5:88)
    at EmbeddedCollection.find (collection.mjs:46:12)
    at eval (eval at _executeScript (foundry.js:16976:16), <anonymous>:5:42)
    at Macro.eval (eval at _executeScript (foundry.js:16976:16), <anonymous>:225:7)
    at Macro._executeScript (foundry.js:16978:10)
    at Macro.execute (foundry.js:16935:21)
    at MacroConfig._onExecute (foundry.js:49797:17)
eval	@	VM23941:5
find	@	collection.mjs:46
eval	@	VM23941:5
eval	@	VM23941:225
_executeScript	@	foundry.js:16978
execute	@	foundry.js:16935
_onExecute	@	foundry.js:49797
await in _onExecute (async)		
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2
```

OS: Windows 10
Browser: Chrome 99.0.4844.51
System: DnD5e 1.5.7
Foundry Version 9.255
Hosted on The Forge

**Comment by Jules-Bens-Aa** [comment]
Sorry for the delay, I've only just noticed this 😅 
We have no idea why you had this error. We couldn't replicate it at all.
I pushed an update (v0.1.4) that should hopefully fix it for you.
Could you let me know please ?
